/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bespin_enet_Event_Type */

#ifndef _Included_org_bespin_enet_Event_Type
#define _Included_org_bespin_enet_Event_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
