/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bespin_enet_Packet_Flag */

#ifndef _Included_org_bespin_enet_Packet_Flag
#define _Included_org_bespin_enet_Packet_Flag
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
