/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bespin_enet_MutableInteger */

#ifndef _Included_org_bespin_enet_MutableInteger
#define _Included_org_bespin_enet_MutableInteger
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bespin_enet_MutableInteger_serialVersionUID
#define org_bespin_enet_MutableInteger_serialVersionUID -8742448824652078965LL
#ifdef __cplusplus
}
#endif
#endif
