/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bespin_enet_Peer */

#ifndef _Included_org_bespin_enet_Peer
#define _Included_org_bespin_enet_Peer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bespin_enet_Peer
 * Method:    throttleConfigure
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_org_bespin_enet_Peer_throttleConfigure
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    send
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_bespin_enet_Peer_send
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    receive
 * Signature: (Ljava/nio/ByteBuffer;Lorg/bespin/enet/MutableInteger;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_bespin_enet_Peer_receive
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    ping
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_bespin_enet_Peer_ping
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    disconnect_now
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_bespin_enet_Peer_disconnect_1now
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    disconnect
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_bespin_enet_Peer_disconnect
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    disconnect_later
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_bespin_enet_Peer_disconnect_1later
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    get_address
 * Signature: (Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bespin_enet_Peer_get_1address
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    get_port
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_bespin_enet_Peer_get_1port
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_bespin_enet_Peer
 * Method:    reset
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_bespin_enet_Peer_reset
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
